version: "3.9"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: comeiaPw
      MYSQL_DATABASE: comeia
      MYSQL_USER: comeia
      MYSQL_PASSWORD: comeiaPw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
