swagger: "2.0"
info:
  version: "1.0.0"
  title: "Lista de Tarefas API"
  description: "API para gerenciar lista de tarefas"
basePath: "/"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Token de autorização Bearer

paths:
  /tasks:
    get:
      tags:
        - "Tasks"
      summary: "Listar tarefas"
      description: "Retorna uma lista de todas as tarefas cadastradas."
      security:
        - BearerAuth: []
      parameters:
        - name: done
          in: query
          description: "Status de execução atual"
          type: boolean
          enum: [true, false]
      responses:
        200:
          description: "Operação bem sucedida"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ListOfTasks"
        500:
          description: "Erro interno do servidor"
    post:
      tags:
        - "Tasks"
      summary: "Criar tarefa"
      description: "Cria uma nova tarefa."
      security:
        - BearerAuth: []
      parameters:
        - name: "task"
          in: "body"
          description: "Objeto Task a ser criado"
          required: true
          schema:
            $ref: "#/definitions/NewTask"
      responses:
        201:
          description: "Tarefa criada com sucesso"
          schema:
            $ref: "#/definitions/TaskCreated"
        400:
          description: "Requisição inválida"
        500:
          description: "Erro interno do servidor"
  /tasks/{task_id}:
    delete:
      tags:
        - "Tasks"
      summary: "Excluir tarefa"
      description: "Exclui uma tarefa a partir do seu ID."
      security:
        - BearerAuth: []
      parameters:
        - name: "task_id"
          in: "path"
          description: "ID da tarefa a ser excluída."
          required: true
          type: "integer"
      responses:
        204:
          description: "Tarefa excluída com sucesso"
        404:
          description: "Tarefa não encontrada"
        500:
          description: "Erro interno do servidor"

    patch:
      tags:
        - "Tasks"
      summary: "Atualizar tarefa"
      description: "Atualiza uma tarefa a partir do seu ID."
      security:
        - BearerAuth: []
      parameters:
        - name: "task_id"
          in: "path"
          description: "ID da tarefa a ser atualizada."
          required: true
          type: "integer"
        - name: "task"
          in: "body"
          description: "Objeto Task a ser atualizado"
          required: true
          schema:
            $ref: "#/definitions/UpdateTask"
      responses:
        200:
          description: "Tarefa atualizada com sucesso"
          schema:
            $ref: "#/definitions/TaskCreated"
        404:
          description: "Tarefa não encontrada"
        500:
          description: "Erro interno do servidor"

  /users/register:
    post:
      tags:
        - "Users"
      summary: "Registro de usuário"
      description: "Realiza a criação do usuário"
      parameters:
        - name: "task"
          in: "body"
          description: "Objeto com as credenciais do usuário"
          required: true
          schema:
            $ref: "#/definitions/NewUser"
      responses:
        201:
          description: "Usuário criada com sucesso"
          schema:
            $ref: "#/definitions/UserCreated"
        400:
          description: "Requisição inválida"
        500:
          description: "Erro interno do servidor"
  /users/login:
    post:
      tags:
        - "Users"
      summary: "Login de usuário"
      description: "Realiza a autenticação do usuário"
      parameters:
        - name: "task"
          in: "body"
          description: "Objeto com as credenciais do usuário"
          required: true
          schema:
            $ref: "#/definitions/NewUser"
      responses:
        201:
          description: "Usuário autenticado com sucesso"
          schema:
            $ref: "#/definitions/UserAuthenticated"
        400:
          description: "Requisição inválida"
        500:
          description: "Erro interno do servidor"        

definitions:
  TaskCreated:
    type: "object"
    properties:
      success:
        type: "string"
        example: "success"
      data:
        type: "object"
        properties:
          task_id:
            type: "string"
            example: "179aa216-6e88-43e8-89e7-09ed5ae54b67"
          date:
            type: "string"
            format: "date-time"
          description:
            type: "string"
            example: "Criar testes de integração e unitários"
          done:
            type: "boolean"
          user_id:
            type: "string"
            example: "179aa216-6e88-43e8-89e7-09ed5ae54b67"
  NewTask:
    type: "object"
    properties:
      date:
        type: "string"
        format: "date-time"
      description:
        type: "string"
      done:
        type: "boolean"
    required: [date, description, done]
  NewUser:
    type: "object"
    properties:
      email:
        type: "string"
        example: "jondoe@email.com"
      password:
        example: "StrongPassword123"
        type: "string"
        minimum: 6
    required: [email, password]
  UserCreated:
    type: "object"
    properties:
      success:
        type: "string"
        example: "success"
      data:
        type: "object"
        properties:
          user_id:
            type: "string"
            example: "179aa216-6e88-43e8-89e7-09ed5ae54b67"
    required:
      - user_id
  UserAuthenticated:
    type: "object"
    properties:
      success:
        type: "string"
        example: "success"
      data:
        type: "string"
        example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVhYTVlNGE1LWU0N2MtNDkyYi04ZmUyLTA1NzJlODc5MzdmYiIsImlhdCI6MTY3NzYwNzMxMCwiZXhwIjoxNjc3NjkzNzEwfQ.7QYDL2vB4D6O0tOeGSto-yEezDWf4WDWTS0D3IjShaM"
        description: "Token Bearer para ser usado no campo Authentication"
    required:
      - user_id    
  ListOfTasks:
    type: "object"
    properties:
      success:
        type: "string"
        example: "success"
      data:
        type: "array"
        items:
          type: "object"
          properties:
            task_id:
              type: "string"
              example: "179aa216-6e88-43e8-89e7-09ed5ae54b67"
            date:
              type: "string"
              format: "date-time"
            description:
              type: "string"
              example: "Criar testes de integração e unitários"
            done:
              type: "boolean"
            user_id:
              type: "string"
              example: "179aa216-6e88-43e8-89e7-09ed5ae54b67"
  UpdateTask:
    type: "object"
    properties:
      date:
        type: "string"
        format: "date-time"
      description:
        type: "string"
      done:
        type: "boolean"
